services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:

      MYSQL_DATABASE: ordersDb
      
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"
      # volumes:      - ./mysql_data:/var/lib/mysql